#!/usr/bin/env python3
"""Regenerate src/physics/data/moons.ts from JPL's planetary satellite tables.

  https://ssd.jpl.nasa.gov/sats/elem/      mean orbital elements (all known moons)
  https://ssd.jpl.nasa.gov/sats/phys_par/  GM, radius, density (moons with measured values)

Run: python3 tools/fetch-moons.py
"""
import html, json, re, urllib.request

def get(url):
    return urllib.request.urlopen(url, timeout=60).read().decode('utf-8')

def table(src, i=0):
    t = re.findall(r'<table.*?</table>', src, re.S)[i]
    rows = re.findall(r'<tr.*?</tr>', t, re.S)
    cell = lambda c: html.unescape(re.sub(r'<.*?>', ' ', c)).split()
    return [[(cell(c) or [''])[0] if True else '' for c in re.findall(r'<t[dh].*?</t[dh]>', r, re.S)] for r in rows]

def num(x):
    try: return float(x)
    except ValueError: return None

elem = table(get('https://ssd.jpl.nasa.gov/sats/elem/'))
phys_rows = table(get('https://ssd.jpl.nasa.gov/sats/phys_par/'))
# each value cell holds "value sigma ref"; the first token is the value
phys = {}
for r in phys_rows:
    if len(r) >= 6 and num(r[2]) is not None:
        phys[r[2]] = (num(r[3]), num(r[4]), num(r[5]))

hdr = elem[0]
col = {h: i for i, h in enumerate(hdr)}
out = []
for r in elem[1:]:
    if len(r) < len(hdr): continue
    # names can be two words (S/2004 S 7); take the full cell text again
    out.append(r)

# re-read names with spaces intact
src = get('https://ssd.jpl.nasa.gov/sats/elem/')
t = re.findall(r'<table.*?</table>', src, re.S)[0]
rows = re.findall(r'<tr.*?</tr>', t, re.S)[1:]
moons = []
for r in rows:
    cells = [' '.join(html.unescape(re.sub(r'<.*?>', ' ', c)).split()) for c in re.findall(r'<t[dh].*?</t[dh]>', r, re.S)]
    if len(cells) < 19: continue
    _, planet, name, code, eph, frame, epoch, a, e, w, M, i, node, P, _, _, ra, dec, tilt = cells[:19]
    gm, rad, rho = phys.get(code, (None, None, None))
    moons.append([planet, name, frame, epoch, num(a), num(e), num(w), num(M), num(i), num(node), num(P),
                  num(ra), num(dec), gm, rad])

with open('src/physics/data/moons.ts', 'w') as f:
    f.write('// Generated by tools/fetch-moons.py from JPL Solar System Dynamics:\n')
    f.write('// mean elements https://ssd.jpl.nasa.gov/sats/elem/ and physical parameters\n')
    f.write('// https://ssd.jpl.nasa.gov/sats/phys_par/. Do not edit by hand.\n')
    f.write('// [planet, name, frame, epoch, a km, e, ω°, M°, i°, node°, P days, pole RA°, pole Dec°, GM km³/s², radius km]\n')
    f.write('export type MoonRow = [string, string, string, string, number, number, number, number, number, number, number, number | null, number | null, number | null, number | null];\n')
    f.write('export const MOONS: MoonRow[] = [\n')
    for m in moons:
        f.write('  ' + json.dumps(m, ensure_ascii=False) + ',\n')
    f.write('];\n')
print(len(moons), 'moons;', sum(1 for m in moons if m[13]), 'with measured GM')
