#!/usr/bin/env python3
"""
Bake the Earth's surface classes from Natural Earth (public domain) into
src/pixel/data/earth.ts: an equirectangular map, 4096 x 2048 (about 10 km a cell), one class per
texel, run-length encoded. The renderer colours and details it.

Classes: 0 ocean, 1 land, 2 ice, 3 desert, 4 lake, 5 mountains, 6 tundra.

    python3 tools/fetch-earth.py            # download and bake
    python3 tools/fetch-earth.py DIR        # bake from geojson already in DIR
"""
import base64, json, os, sys, urllib.request

W, H = 4096, 2048
BASE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/'
LAYERS = ['ne_50m_land', 'ne_50m_glaciated_areas', 'ne_50m_lakes', 'ne_50m_geography_regions_polys']


def load(name, src):
    path = os.path.join(src, name + '.geojson') if src else None
    if path and os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    with urllib.request.urlopen(BASE + name + '.geojson', timeout=120) as r:
        return json.load(r)


def rings_of(geom):
    if geom is None:
        return []
    if geom['type'] == 'Polygon':
        return geom['coordinates']
    if geom['type'] == 'MultiPolygon':
        return [ring for poly in geom['coordinates'] for ring in poly]
    return []


def fill(grid, rings, cls, only=None):
    """even-odd scanline fill of a set of rings (one feature) into the grid"""
    rows = [[] for _ in range(H)]
    for ring in rings:
        pts = [((lon + 180) / 360 * W, (90 - lat) / 180 * H) for lon, lat in ring]
        for (x1, y1), (x2, y2) in zip(pts, pts[1:] + pts[:1]):
            if y1 == y2:
                continue
            lo, hi = min(y1, y2), max(y1, y2)
            for j in range(max(0, int(lo)), min(H, int(hi) + 1)):
                yc = j + 0.5
                if lo <= yc < hi:
                    rows[j].append(x1 + (yc - y1) * (x2 - x1) / (y2 - y1))
    for j, xs in enumerate(rows):
        xs.sort()
        for a, b in zip(xs[0::2], xs[1::2]):
            for i in range(max(0, int(a + 0.5)), min(W, int(b + 0.5))):
                if only is None or grid[j][i] in only:
                    grid[j][i] = cls


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    grid = [[0] * W for _ in range(H)]
    land, ice, lakes, regions = (load(n, src) for n in LAYERS)
    for f in land['features']:
        fill(grid, rings_of(f['geometry']), 1)
    for f in regions['features']:
        p = f['properties']
        cla = p.get('FEATURECLA') or p.get('featurecla')
        if cla == 'Range/mtn':
            fill(grid, rings_of(f['geometry']), 5, only={1})
        elif cla == 'Tundra':
            fill(grid, rings_of(f['geometry']), 6, only={1})
    for f in regions['features']:
        p = f['properties']
        if (p.get('FEATURECLA') or p.get('featurecla')) == 'Desert':
            fill(grid, rings_of(f['geometry']), 3, only={1, 5})
    for f in ice['features']:
        fill(grid, rings_of(f['geometry']), 2, only={1, 3, 5, 6})
    for f in lakes['features']:
        fill(grid, rings_of(f['geometry']), 4, only={1, 2, 3, 5, 6})
    # run-length: a byte for the class and a byte for the run (up to 255), base64
    out = bytearray()
    for row in grid:
        i = 0
        while i < W:
            c, n = row[i], 1
            while i + n < W and row[i + n] == c and n < 255:
                n += 1
            out += bytes([c, n])
            i += n
    b64 = base64.b64encode(bytes(out)).decode()
    dst = os.path.join(os.path.dirname(__file__), '..', 'src', 'pixel', 'data', 'earth.ts')
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, 'w') as f:
        f.write('// Generated by tools/fetch-earth.py from Natural Earth (public domain). Do not edit.\n')
        f.write(f'/** The Earth\'s surface classes, {W} x {H}, equirectangular from 180 W, north at the top, run-length encoded */\n')
        f.write(f'export const EARTH_W = {W}, EARTH_H = {H};\n')
        f.write('export const EARTH_RLE =\n')
        for k in range(0, len(b64), 120):
            f.write(f"  '{b64[k:k + 120]}'" + (' +\n' if k + 120 < len(b64) else ';\n'))
    print(f'{len(out) // 2} runs, {len(b64)} chars -> {dst}')


if __name__ == '__main__':
    main()
